# Generated by Django 5.1.7 on 2025-03-27 10:49
import django.db.models.deletion
from django.db import migrations, models

def create_default_forum(apps, schema_editor):
    Forum = apps.get_model('blogs', 'Forum')
    Forum.objects.create(name="Faith & Spirituality", description="My religious journey, Faith & Doubt")

class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(create_default_forum),  # Adds a default forum
        migrations.RemoveField(
            model_name='blogpost',
            name='topic',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.forum'),
        ),
    ]