# Generated by Django 5.1.7 on 2025-06-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_forum_created_at_alter_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photos/'),
        ),
    ]
