# Generated by Django 5.1.7 on 2025-06-09 05:13

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogpost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.unique_blog_photo_path),
        ),
    ]
